// Package web serves the embedded frontend. dist/ is populated by `make
// web-build` (or the Dockerfile's frontend build stage) before `go build`;
// in a fresh checkout it holds only .gitkeep, and SPAHandler serves a plain
// "not built yet" message instead of failing to compile or panicking.
package web

import (
	"embed"
	"io/fs"
	"net/http"
	"path"
	"strings"

	"github.com/labstack/echo/v4"
)

//go:embed all:dist
var embedded embed.FS

const distDir = "dist"

// distFS strips the "dist" prefix so paths match what the browser requests
// ("/assets/index.js", not "/dist/assets/index.js").
func distFS() fs.FS {
	sub, err := fs.Sub(embedded, distDir)
	if err != nil {
		return embedded // unreachable in practice (distDir is a compile-time constant that always exists)
	}
	return sub
}

// SPAHandler serves the built frontend: a real file if the request path
// matches one, otherwise index.html (client-side routing fallback). Returns
// a plain message if the frontend hasn't been built yet (dist/ has only
// .gitkeep) rather than a broken 404 loop.
func SPAHandler() echo.HandlerFunc {
	assets := distFS()
	return func(c echo.Context) error {
		reqPath := strings.TrimPrefix(c.Request().URL.Path, "/")
		if reqPath == "" {
			reqPath = "index.html"
		}
		if data, err := fs.ReadFile(assets, reqPath); err == nil {
			return c.Blob(http.StatusOK, contentType(reqPath), data)
		}
		// Not a real asset path -> SPA fallback to index.html.
		if data, err := fs.ReadFile(assets, "index.html"); err == nil {
			return c.HTMLBlob(http.StatusOK, data)
		}
		return c.String(http.StatusOK, "RouterLens — frontend not built yet (run `make web-build`)")
	}
}

// contentType maps a handful of known static-asset extensions; anything else
// falls back to octet-stream (the SPA's own asset filenames are always one
// of these, generated by Vite's build).
func contentType(p string) string {
	switch path.Ext(p) {
	case ".html":
		return "text/html; charset=utf-8"
	case ".js":
		return "text/javascript; charset=utf-8"
	case ".css":
		return "text/css; charset=utf-8"
	case ".svg":
		return "image/svg+xml"
	case ".json":
		return "application/json; charset=utf-8"
	case ".woff2":
		return "font/woff2"
	case ".ico":
		return "image/x-icon"
	case ".png":
		return "image/png"
	case ".webp":
		return "image/webp"
	default:
		return "application/octet-stream"
	}
}
